// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fagsiedxurvhubqrbckd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZhZ3NpZWR4dXJ2aHVicXJiY2tkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzNTk4ODUsImV4cCI6MjA1MzkzNTg4NX0.JPEHTmuOs6v-VPo4w9v4BWHq3Z462KA4R0t_-b1EU7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);